// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migratsiyalar uchun direct (non-pooling) ulanish kerak — PgBouncer ba'zi DDL ni qo'llamaydi.
    // Lokal dev'da DATABASE_URL ishlaydi.
    url:
      process.env["POSTGRES_URL_NON_POOLING"] ??
      process.env["DATABASE_URL"] ??
      process.env["POSTGRES_URL"],
  },
});
